<?php 
if (isset($_GET['logout'])) {
	//Logout System
	// Initialize the session.
	// If you are using session_name("something"), don't forget it now!
	require_once '../dblogins.php';
	session_start();

	$conn = new mysqli($db_hostname, $db_username, $db_password, $db_database);
	// Check connection
	if ($conn->connect_error) {
	die("Connection failed, please contact support");
	}
	$query = "UPDATE tokens SET valid = '0' WHERE token = '" . $_SESSION['token'] . "'";
	$result = $conn->query($query);
	// Unset all of the session variables.
	$_SESSION = array();
	// If it's desired to kill the session, also delete the session cookie.
	// Note: This will destroy the session, and not just the session data!
	if (ini_get("session.use_cookies")) {
		$params = session_get_cookie_params();
		setcookie(session_name(), '', time() - 42000,$params["path"], $params["domain"],$params["secure"], $params["httponly"]);
	}
	// Finally, destroy the session.
	session_destroy();
	echo '<div class="modal show" id="logoutbox" role="dialog">
			<div class="modal-dialog">
			
			  <!-- Modal content-->
			  <div class="modal-content">
				<div class="modal-header">
					<h4 class="modal-title">Logout Successful</h4>
				</div>
				<div class="modal-body">
					<center><p>You have successfully been logged out of AuthEagle - Have a nice day!</p></center>
					<center><img src="//www.autheagle.com/img/required_for_error_pages/eaglehunting.gif" style="width: 100%;" alt="Eagle Hunting" /></center>
				</div>
				<div class="modal-footer">
					<i>Image from BBC Television</i>
				</div>
			  </div>
			  
			</div>
		  </div>';
	
} if (isset($_GET['return'])) {
	session_set_cookie_params(0, '/', '.autheagle.com');
	session_start();
	$_SESSION['returnurl'] = urldecode($_GET['return']);
}
?>
<!DOCTYPE html>
<html>
	<head>
	<title>AuthEagle Login</title>
	<meta content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" name="viewport">
	
	<link href="//fonts.googleapis.com/css?family=Lato:100,300,400,700" media="all" rel="stylesheet" type="text/css" />
	<link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css" media="all" rel="stylesheet" type="text/css" />
	<link href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" media="all" rel="stylesheet" type="text/css" />
	<link href="stylesheets/loginstylefont.css" media="all" rel="stylesheet" type="text/css" />
	<link href="stylesheets/loginstyle.css" media="all" rel="stylesheet" type="text/css" />
	
	<script src="//code.jquery.com/jquery-1.10.2.min.js" type="text/javascript"></script>
	<script src="//code.jquery.com/ui/1.10.3/jquery-ui.js" type="text/javascript"></script>
	<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js" type="text/javascript"></script>
	<script src="//cdnjs.cloudflare.com/ajax/libs/bootbox.js/4.4.0/bootbox.min.js" type="text/javascript"></script>
	<script>
	$(document).ready(function() {
		/*AUTHEAGLE LOGIN STUFF*/
		function autheaglelogin(twostep) {
			if (typeof twostep === 'undefined') {
				twostep = false;
			}
			//Function to Login with AuthEagle
			if ($("#user").val().length <= 0 || $("#pass").val().length <= 0) {
				bootbox.alert("Please make sure your username and password are enterd into the boxes to login!");
			} else {
				result = "";
				$("#loginbox").fadeTo(1000, 0.01);
				$("#usernameorpasswordincorrect").fadeTo(1000, 0.01);
				$("#loading").fadeIn(10000);
				$.ajax({
					url: "loginwith/autheagle/", 
					type: "POST",
					dataType: "text",
					data: ("user=" + $("#user").val() + "&pass=" + $("#pass").val() + ((twostep !== false) ? "&2stepcode=" + twostep : "")),
					success: function(result) {
						if (result == "2") {
							$("#loginbox").fadeTo(100, 1);
							$("#usernameorpasswordincorrect").fadeTo(100, 1);
							$("#loading").hide();
							
						} else if (result == "1") {
							window.location.href = "/";
						} else if (result == "3") {
							//2 step code needed
							$(document.body).append('<?php echo preg_replace( "/\r|\n/", "", '
												<div class="modal fade" id="twostepmodal" role="dialog">
												<div class="modal-dialog">
												
												  <!-- Modal content-->
												  <div class="modal-content">
													<div class="modal-header">
														<h4 class="modal-title">Setup 2Step Verification</h4>
													</div>
													<div class="modal-body">
														<img scr="/images/connect%20with%20icons/phone_with_google_app.png" alt="App Code" /><p>Please enter the code generated by the Google Authenticator App:</p>
														<input type="number" maxlength="6" class="form-control" id="twostepfield" placeholder="App Code" />
														<br/><br/>
														<i>Having Trouble? <a href="mailto:support@autheagle.com">Contact Support</i></a>
													</div>
													<div class="modal-footer">
														<button id="twosteploginbutton" class="btn btn-primary" data-dismiss="modal">Login</button>
													</div>
												  </div>
												  
												</div>
											  </div>'); ?>');
							$('#twostepmodal').modal('show');
							$('#twostepmodal').on('hidden.bs.modal', function (e) {
								autheaglelogin($("#twostepfield").val());
							});
						} else if (result == "4") {
							//2 step code needed
							$(document.body).append('<?php echo preg_replace( "/\r|\n/", "", '
												<div class="modal fade" id="twostepmodal" role="dialog">
												<div class="modal-dialog">
												
												  <!-- Modal content-->
												  <div class="modal-content">
													<div class="modal-header">
														<h4 class="modal-title">Setup 2Step Verification</h4>
													</div>
													<div class="modal-body">
														<b>2Step Verification Code Incorrect - Please try again</b>
														<img scr="/images/connect%20with%20icons/phone_with_google_app.png" alt="App Code" /><p>Please enter the code generated by the Google Authenticator App:</p>
														<input type="number" maxlength="6" class="form-control" id="twostepfield" placeholder="App Code" />
													</div>
													<div class="modal-footer">
														<button id="twosteploginbutton" class="btn btn-primary" data-dismiss="modal">Login</button>
														<br/><br/>
														<i>Having Trouble? <a href="mailto:support@autheagle.com">Contact Support</i></a>
													</div>
												  </div>
												  
												</div>
											  </div>'); ?>');
							$('#twostepmodal').modal('show');
							$('#twostepmodal').on('hidden.bs.modal', function (e) {
								autheaglelogin($("#twostepfield").val());
							});
						} else {
							$("#loginbox").fadeTo(100, 1);
							bootbox.alert(result + "<br/><br/><br/>You may wish to contact support@autheagle.com for more help.");
						}
					},
					error: function(){
						bootbox.alert("Sorry, we are unable to log you in at this time<br/><br/><br/>Please refresh this page and check your internet connection");
					}
				});
			}
		}
		//Enter Key - Username Box
		$('#user').keyup(function(e){
			if(e.keyCode == 13) {
			  autheaglelogin();
			}
		});
		//Enter Key - Password Box
		$('#pass').keyup(function(e){
			if(e.keyCode == 13) {
			  autheaglelogin();
			}
		});
		//Button Click
		$("#loginbutton").click(function() {
 			autheaglelogin();
		});
		/*END - AUTHEAGLE LOGIN STUFF*/
	});
	</script>

	</head>
	<body class="login2">
	<!-- Login Screen -->
		<div class="login-wrapper">
			<a href="//www.autheagle.com"><img style="width: 150px;" alt="AuthEagle Logo" src="/images/logo/150.png" /></a>
			
			<!--Sort of Form-->
			<div id="loginbox">
				<div id="usernameorpasswordincorrect" style="display: none;">
					<center><i>Username or Password incorrect</i></center>
				</div>
				<div class="form-group">
					<div class="input-group">
					<span class="input-group-addon"><i class="fa fa-envelope"></i></span><input class="form-control" id="user" placeholder="Username or Email" type="text">
					</div>
				</div>
				<div class="form-group">
					<div class="input-group">
					<span class="input-group-addon"><i class="fa fa-lock"></i></span><input class="form-control" id="pass" placeholder="Password" type="password">
					</div>
				</div>
				<a class="pull-right" href="#">Forgot password?</a>
				<div class="text-left">
					<!--<label class="checkbox"><input type="checkbox"><span>Keep me logged in</span></label>-->
				</div>
				<input type="hidden" name="return" value="<?php if (isset($_GET['return'])) echo $_GET['return']; ?>" />
				<button class="btn btn-lg btn-primary btn-block" id="loginbutton">Log in</button>
				
			</div>
			<div id="loading" style="display: none;">
				Having trouble logging in? <a href="mailto:support@autheagle.com">Contact Support</a>
			</div>
			<!--End Form-->
			<div class="social-login clearfix">
				<a class="btn btn-primary pull-left facebook" href="loginwith/facebook/"><i class="fa fa-facebook"></i>Login with facebook</a><a class="btn btn-primary pull-right twitter" href="loginwith/twitter/"><i class="fa fa-twitter"></i>Login with twitter</a>
			</div>
			<p>
			Don't have an account yet?
			</p>
			<a class="btn btn-default-outline btn-block" href="signup.php">Sign up now</a>
		</div>

	<!-- End Login Screen -->
	</body>
</html>